#Reverse a string using loop.
#Using While Loop
Sen=input("Enter a string: ")
rev=""
slen=len(Sen)-1
while slen>=0:
    rev+=Sen[slen]
    slen-=1
print("The reversed String is: ",rev)
print("This Output is generated using while loop")

#Using For loop
s=input("Enter a String: ")
Rev=""
for char in s:
    Rev=char+Rev
print("the reversed String is: ",Rev)
print("This Output is generated by for loop")